server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: message-service
          uri: http://message-service.default.svc.cluster.local:8080
          predicates:
            - Path=/message-service/**
          filters:
            - RewritePath=/message-service/(?<path>.*), /${path}
        - id: user-service
          uri: http://user-service.default.svc.cluster.local:8080
          predicates:
            - Path=/user-service/**
            - Path=/user/**          # Добавьте этот путь, если необходимо
          filters:
            - RewritePath=/user-service/(?<path>.*), /${path}
        - id: oauth2-service
          uri: http://user-service.default.svc.cluster.local:8080
          predicates:
            - Path=/oauth2/**
        - id: oauth2-redirect
          uri: http://user-service.default.svc.cluster.local:8080
          predicates:
            - Path=/login/oauth2/code/**
        - id: model-service
          uri: http://model-service.default.svc.cluster.local:8080
          predicates:
            - Path=/model-service/**
          filters:
            - RewritePath=/model-service/(?<path>.*), /${path}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
